import recommenderSystem from './recommenderSystem.jpeg'
import RecycleNet from './RecycleNet.png'
import ChatBot from './ChatBot.jpeg'
import SentimentAnalysis from './SentimentAnalysis.jpeg'
import ProfilePic from './ProfilePic.jpg'
import VideoGames from './pc.jpg'
import Addons from './TFAddons.jpg'
import WeightLifting from './WeightLifting.jpg'
import Books from './books.jpeg'
import Movies from './Movies.jpg'
import Chess from './Chess.jpeg'
import Programming from './Programming.jpeg'
import Billiards from './Billiards.jpeg'

export { Billiards, Programming, Chess, Movies, WeightLifting, Addons, recommenderSystem, RecycleNet, ChatBot, SentimentAnalysis, ProfilePic, VideoGames, Books}